In [1]:
## initialy lets import numpy
import numpy as np

In [2]:
my_list=[1,2,3,4,5]

In [3]:
arr=np.array(my_list)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
#checking the shape
## to tell numbers of rows and columns use variable.shape
arr.shape

(5,)

In [7]:
#multinested array
my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,10]
my_list3=[11,12,13,14,15]
arr1=np.array([my_list1,my_list2,my_list3])

In [8]:
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
arr1.shape

(3, 5)

In [11]:
#Reshaping the array
arr1.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

### Indexing

In [12]:
## Accessing the array Element

In [13]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [14]:
print(arr)

[1 2 3 4 5 6 7 8 9]


In [15]:
arr[3]

4

In [16]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [19]:
arr1[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [21]:
arr1[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

In [24]:
arr1[1:2,1:4]

array([[7, 8, 9]])

In [26]:
arr1=np.arange(0,10)

In [27]:
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
arr1=np.arange(0,10,step=3)

In [29]:
print(arr1)

[0 3 6 9]


In [30]:
print(np.linspace(1,10,100))

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [34]:
### Some conditions very useful in Exploratory Data Analysis
val=2
arr1[arr1<val]


array([0])

In [35]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [36]:
np.ones((2,5),dtype=float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])